entrypoint: gunicorn -b :$PORT postsproject.wsgi
env: flex
runtime: python

env_variables:
  DEBUG: 'False'
  DEPLOY_HOST: "django-test-202211.appspot.com"

handlers:
- url: /static
  static_dir: static